### ISSUE TITLE
Little things count... Links

### ISSUE THREAD

**Issue by ehelldane** [PopcornTimeCE/desktop#12]
Please consider fixing links and version info, on the info screen.
![untitled-2](https://cloud.githubusercontent.com/assets/16136002/11562459/17927622-999c-11e5-858c-f93e39dfbee6.jpg)

**Comment by ehelldane** [comment]
new to git, was looking at some code, looks like some of this has already been done here, but hasn't been pushed to the release yet? maybe i should stick to discuss.popcorntime.ml

**Comment by gungale1** [comment]
Yes, this has already been fixed in the current commit.
