### ISSUE TITLE
PopcornTimeCE is repeating previous PopcornTime forks mistake.

### ISSUE THREAD

**Issue by JonasNo** [PopcornTimeCE/desktop#14]
The source code repo isn't mirrored. Github is a known coward that accepts any false DMCA claims it gets.

Please be smarter than the previous PopcornTime teams, mirror the source code repo on other sites.

Hail Hydra!

**Comment by Cloudfight** [comment]
Yes, we will but we are in an early state right now so it will take some time

**Comment by gungale1** [comment]
Same
