### ISSUE TITLE
Question: Zipping - What is being created?

### ISSUE THREAD

**Issue by Geyup** [PopcornTimeCE/desktop#17]
at the end of running, ```npm run build:YOUR_OS``` it starts zipping, what is being created here when it's zipping?

thank you

**Comment by joshualawson** [comment]
This project uses Node Webkit, or recently renamed to NW.js

To package the application it compresses all the code into a zip.

more info can be found at http://nwjs.io/

**Comment by gungale1** [comment]
This is not an issue. Questions like this should be directed to http://discuss.popcorntime.ml. But I'm glad you got your answer.

**Comment by Geyup** [comment]
Yes it's not an issue, that's why I put ```Question``` some developers don't mind some questions on their projects, that's why I asked here...

thank you...
