### ISSUE TITLE
Wrong permissions?

### ISSUE THREAD

**Issue by Geyup** [PopcornTimeCE/desktop#22]
Hi I noticed that ```icudtl.dat libffmpegsumo.so nw.pak``` are being created as executable...

Shouldn't these be 644?

thanks

**Comment by Geyup** [comment]
I just noticed also the ```locales``` all the ```.pak``` are executable too...

**Comment by micopiira** [comment]
nw-builder issue I think. Try posting an issue there.

**Comment by Geyup** [comment]
URL?
