### ISSUE TITLE
npm WARN deprecated

### ISSUE THREAD

**Issue by Geyup** [PopcornTimeCE/desktop#23]
Seeing deprecated messages at compile time;

npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

npm WARN deprecated URIjs@1.16.1: package renamed to "urijs" (lower-case), please update accordingly

npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

**Comment by gungale1** [comment]
urijs was fixed in a previous commit, we'll look into the others.

**Comment by Geyup** [comment]
I grabbed the latest commit, so I'm not sure why it's still complaining about URIjs...

hmm

**Comment by micopiira** [comment]
```
...
├─┬ torrent-tracker-health@0.1.4
│ ├── async@1.5.0
│ ├── q@1.4.1
│ └─┬ torrent-tracker@0.0.7
│   ├── bencode@0.7.0
│   └── URIjs@1.16.1
...
```

URIjs is a dependency of [torrent-tracker-health](https://www.npmjs.com/package/torrent-tracker-health) package. So this issue can be closed.

**Comment by Geyup** [comment]
@micopiira I'm not talking about it being a dependancy, I'm talking about the misspelling, how it's suppose to now be in ```lowercase```

Looking at the package.json it was changed; ```"urijs": "^1.17.0",``` but when compiling, the ```Issue``` is that it's still complaining...

hmm

**Comment by micopiira** [comment]
It is complaining simply because it is being installed by another dependency that PopcorntimeCE depends on. So the warning is not related to this project. As you can see PopcorntimeCE depends on torrent-tracker-health which depends on torrent-tracker and it depends on URIjs. So torrent-tracker package needs to update its package.json or PopcorntimeCE should drop or fork torrent-tracker to get the warning away unless they change it themselves

**Comment by Geyup** [comment]
Ahhh sorry my bad for not paying better attention to the output you posted above.

**Comment by Geyup** [comment]
@micopiira I forgot to ask, do you have an URL for the torrent-tracker? And I'll report the issue with them.

**Comment by micopiira** [comment]
@Geyup https://www.npmjs.com/package/torrent-tracker heres link to the package, its git repository seems to be down. So someone (Maybe @PopcornTimeCe ?) should rehost it in github or something.

**Comment by gungale1** [comment]
done: https://github.com/PopcornTimeCE/torrent-tracker-health

**Comment by micopiira** [comment]
@gungale1 torrent-tracker , not torrent-tracker-health :P

And it's git repository is down, so you would need to install it through npm and create a repo for it.

**Comment by micopiira** [comment]
You also need to *create a new repo* for torrent-tracker, because its own git repository is down. So you would need to download it through npm and rehost it, then change **PopcornTimeCe/torrent-tracker-health** to depend on **your** torrent-tracker package.

**Comment by gungale1** [comment]
@micopiira I did both didn't I? Just linked the one. https://github.com/PopcornTimeCE/torrent-tracker. I actually just forked butterproject's since the only changes made were informative.

**Comment by micopiira** [comment]
@gungale1 Oh yeah, looks good. And the warning is gone too.

**Comment by Geyup** [comment]
I'm lost, why did you go to all the trouble to make a repo here for it?

**Comment by micopiira** [comment]
@Geyup Because the original  torrent-tracker npm package was no longer maintained (The Git repository is gone). So if the package has any bugs/problems they can be fixed (For example the URIjs dependency). That's why.

**Comment by Geyup** [comment]
ok thanks
