### ISSUE TITLE
Mouse Over Icons Not Changing...

### ISSUE THREAD

**Issue by Geyup** [PopcornTimeCE/desktop#24]
I compiled from source in Slackware, so not sure if this is Linux related or not.

I noticed if I move the mouse to the edge for adjusting the GUI size, then the mouse cursor changes as it should, but if I bring the mouse back to some place on the GUI, it doesn't automatically change back to a pointer, unless I click on the GUI window somewhere.

The same also happens when the hand appears, I have to click the GUI in order to bring it back to a pointer.

**Comment by Geyup** [comment]
Sorry, this was only happening when running Slackware in Virtualbox as a guest OS testing out popcorntime in it.

In my host system it appears to be working fine.

**Comment by streger** [comment]
Close this issue than, that would be too much to figure out what's going on and it's related to Virtualbox and as such should be reported on their issue tracker.

**Comment by sundaysan** [comment]
Close this issue than, that would be too much to figure out what's going on and it's related to Virtualbox and as such should be reported on their issue tracker.
