### ISSUE TITLE
"VIDEOJS:" "ERROR:" "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)"

### ISSUE THREAD

**Issue by develroo** [PopcornTimeCE/desktop#25]
Platform Linux amd64. Everything else works very smooth. And the file  plays perfectly in mpv. What am I missing here? Something to do with the build?

EDIT: Forget it. Just noticed settings.js and Settings.chosenPlayer = 'local';

All fixed :)

**Comment by weisk** [comment]
so... what should it be instead of 'local' ? I cant open in-app settings either, it gives me the error `[ERROR] TypeError: undefined is not a function TypeError: undefined is not a function
    at Backbone.Marionette.LayoutView.extend.showSettings (app://host/src/app/lib/views/main_window.js:415:32)`

**Comment by develroo** [comment]
I just set it to mpv

Settings.chosenPlayer = 'mpv';

mpv played the downloaded streams fine. It is just the internal player that seemed not to.

**Comment by kjthegod** [comment]
@develroo what format is the video?

**Comment by develroo** [comment]
Was a 1080p x264 mp4. Like I say worked fine with mpv (I played it from the cache folder) but it would complain about not having the correct format with the internal player. Setting it to mpv though solved it all. So not an issue really. Just surprised me it did not work out of the box.

**Comment by kewitz** [comment]
I can't manage to use the local player and I'm getting this same error on my Linux64 machine.
How can I run the dev mode with local player support?

**Comment by develroo** [comment]
Like I explained:

set it to mpv in desktop/src/app/settings.js

Settings.chosenPlayer = 'mpv';

it can be any player vlc or mplayer etc.

**Comment by kewitz** [comment]
Sorry, I don't think I expresses myself enough.
Is it possible to use the HTML5 PopcornTime VideoJS player?

**Comment by kjthegod** [comment]
Not yet, no. But I'm working on a solution. I have compiled binaries for Linux x64 that are able to play pretty much any audio/video format you can think of. These still need to be compiled for other architectures and platforms though and have not been distributed with Popcorn Time Community Edition yet.

**Comment by kjthegod** [comment]
You can, however, use an external video player and they will work just fine. I recommend VLC. I know it's annoying, but there is a fix in the works.

**Comment by kewitz** [comment]
Any instructions on how to compile my own binaries on Linux x64?

**Comment by weisk** [comment]
Yeah, in my case I wanted to cast to chromecast, so I found out you can put the ip address of the chromecast device there:

`Settings.chosenPlayer = '192.168.1.36';`

You can list all popcorntime associated players using developer tools and the following line:

`_.pluck(App.Device.Collection.models,'id')`

@kewitz, there is plenty of instructions on how to build binaries on any platform. Look at the [README.md](../blob/master/README.md),

> ### Building
>
> 1. `npm install`
> 1. `npm run build:YOUR_OS` For example: `npm run build:osx64` (osx32, osx64, win32, win64, linux32 or linux64)
> 1. The executables should be in the newly created build/ directory

**Comment by kjthegod** [comment]
No that is not correct. I'm referring to the NW.js binaries, not the PTCE binaries. It's the NW.js binary that runs PT that is the culprit, not PT itself.

I'll release my build method later. You can see the order I've decided to do things in here: https://discuss.popcorntime.ml/t/resolve-issue-regarding-video-and-or-audio-playback/627

**Comment by weisk** [comment]
Oh, I was answering his question, I didn't understand he meant nw.js binaries. My bad ;P

**Comment by kjthegod** [comment]
No problem. We're just talking about two separate issues at the same time. That can lead to confusion.

**Comment by kewitz** [comment]
@weisk yep, I'm familiar with building the Popcorn app, thanks. :smile:
@kjthegod Yep, I've already looked into that. I'll check on how to build the NWjs then. :+1:
