### ISSUE TITLE
Clean up package.json file

### ISSUE THREAD

**Issue by micopiira** [PopcornTimeCE/desktop#4]
Why do the dev dependencies include bower and grunt, even if there is no bower/grunt files present?

**Comment by carmona** [comment]
+1

**Comment by fmsouza** [comment]
+1

**Comment by micopiira** [comment]
And to the author, **why** exactly did you take out bower/grunt and decided to put the built files to the repository?

And how are you supposed to build this project without *nw-builder* etc?

**Comment by micopiira** [comment]
https://github.com/PopcornTimeCE/desktop/commit/d2b18f99db32f8756673b9d9120bc71df1f850e3

Heres a PR

**Comment by gungale1** [comment]
Bower/grunt was never there in the first place, and I said I put them there temporarily. Thank you for your PR
