### ISSUE TITLE
Not compatible with node v4.0.0+

### ISSUE THREAD

**Issue by fmsouza** [PopcornTimeCE/desktop#8]
Dependence ```json-rpc2@0.8.1``` currently depends on ```{"node":"0.10.x"}```.

**Comment by micopiira** [comment]
Isnt it a warning only? Does it affect anything?

**Comment by fmsouza** [comment]
I though it was only a warning, but for some reason it stopped the ```npm install``` with error after this warning. And there were no other warnings.

**Comment by hadim** [comment]
a gruntfile is missing ... is that excepted ?

**Comment by jneumann** [comment]
There are a few warnings about node and lodash warnings, but everything installs on my machine (node 4.2.1)

**Comment by micopiira** [comment]
It is expected because grunt is not used at the moment as mentioned by @gungale1 here https://github.com/PopcornTimeCE/desktop/issues/4 the readme should be updated tho.

**Comment by gungale1** [comment]
Everything **should** be working from clone now.
